// generated by stringer -type=Status; DO NOT EDIT

package p2pubapi

import "fmt"

const _Status_name = "NoneInPreparationInServiceStoppedConfiguringStartingRunningStoppingLockedAttachedNotAttachedInitializingArchivingInitializedConfiguredUpdating"

var _Status_index = [...]uint8{0, 4, 17, 26, 33, 44, 52, 59, 67, 73, 81, 92, 104, 113, 124, 134, 142}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
